In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df=pd.read_csv(r"C:\Users\212466649\jupyter\Course End Projects\2) Amazon.com - Employee Access\Dataset for the project\train\train.csv")

In [5]:
df.head()

ACTION  RESOURCE  MGR_ID  ROLE_ROLLUP_1  ROLE_ROLLUP_2  ROLE_DEPTNAME  \
0       1     39353   85475         117961         118300         123472   
1       1     17183    1540         117961         118343         123125   
2       1     36724   14457         118219         118220         117884   
3       1     36135    5396         117961         118343         119993   
4       1     42680    5905         117929         117930         119569   

   ROLE_TITLE  ROLE_FAMILY_DESC  ROLE_FAMILY  ROLE_CODE  
0      117905            117906       290919     117908  
1      118536            118536       308574     118539  
2      117879            267952        19721     117880  
3      118321            240983       290919     118322  
4      119323            123932        19793     119325

In [6]:
df.shape

(32769, 10)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32769 entries, 0 to 32768
Data columns (total 10 columns):
ACTION              32769 non-null int64
RESOURCE            32769 non-null int64
MGR_ID              32769 non-null int64
ROLE_ROLLUP_1       32769 non-null int64
ROLE_ROLLUP_2       32769 non-null int64
ROLE_DEPTNAME       32769 non-null int64
ROLE_TITLE          32769 non-null int64
ROLE_FAMILY_DESC    32769 non-null int64
ROLE_FAMILY         32769 non-null int64
ROLE_CODE           32769 non-null int64
dtypes: int64(10)
memory usage: 2.5 MB


In [11]:
correlation_matrix=df.corr()
correlation_matrix

ACTION  RESOURCE    MGR_ID  ROLE_ROLLUP_1  ROLE_ROLLUP_2  \
ACTION            1.000000  0.000185 -0.005167      -0.013702       0.005179   
RESOURCE          0.000185  1.000000  0.011088      -0.005016       0.013438   
MGR_ID           -0.005167  0.011088  1.000000      -0.007132      -0.000364   
ROLE_ROLLUP_1    -0.013702 -0.005016 -0.007132       1.000000       0.033358   
ROLE_ROLLUP_2     0.005179  0.013438 -0.000364       0.033358       1.000000   
ROLE_DEPTNAME     0.001025  0.030004 -0.009551      -0.009548      -0.006056   
ROLE_TITLE       -0.010169  0.002936  0.017864       0.010207       0.008305   
ROLE_FAMILY_DESC  0.003565  0.021029 -0.018488      -0.007546       0.018873   
ROLE_FAMILY       0.000502  0.031060 -0.118254       0.029468       0.069558   
ROLE_CODE         0.017147  0.007733 -0.004067      -0.024927       0.015117   

                  ROLE_DEPTNAME  ROLE_TITLE  ROLE_FAMILY_DESC  ROLE_FAMILY  \
ACTION                 0.001025   -0.010169          0.003565     0.000502   
RESOURCE               0.030004    0.002936          0.021029     0.031060   
MGR_ID                -0.009551    0.017864         -0.018488    -0.118254   
ROLE_ROLLUP_1         -0.009548    0.010207         -0.007546     0.029468   
ROLE_ROLLUP_2         -0.006056    0.008305          0.018873     0.069558   
ROLE_DEPTNAME          1.000000   -0.006932         -0.002877     0.031669   
ROLE_TITLE            -0.006932    1.000000          0.170692    -0.012450   
ROLE_FAMILY_DESC      -0.002877    0.170692          1.000000    -0.180596   
ROLE_FAMILY            0.031669   -0.012450         -0.180596     1.000000   
ROLE_CODE              0.010319    0.155920          0.092980    -0.148625   

                  ROLE_CODE  
ACTION             0.017147  
RESOURCE           0.007733  
MGR_ID            -0.004067  
ROLE_ROLLUP_1     -0.024927  
ROLE_ROLLUP_2      0.015117  
ROLE_DEPTNAME      0.010319  
ROLE_TITLE         0.155920  
ROLE_FAMILY_DESC   0.092980  
ROLE_FAMILY       -0.148625  
ROLE_CODE          1.000000

In [18]:
df['ACTION'].unique()

array([1, 0], dtype=int64)

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.metrics import accuracy_score,confusion_matrix

In [30]:
x=df.drop('ACTION',axis=1)
y=df['ACTION']

In [31]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=101)

## 1) Logistic Regression Model


In [37]:
Log_model=LogisticRegression()
Log_model.fit(x_train,y_train)
log_y_pred=Log_model.predict(x_test)
print("Logistic Regression accuracy score",accuracy_score(y_test,log_y_pred))

print("Confusion Matrix")
print(confusion_matrix(y_test,log_y_pred))
print("From Confusion matrix Model looks to be biased for label 1, So need to check with other models")

Logistic Regression accuracy score 0.939985759332723
Confusion Matrix
[[   0  590]
 [   0 9241]]
From Confusion matrix Model looks to be biased for label 1, So need to check with other models


## 2) Random Forest Classifier

In [39]:
random_forest_classifier=RandomForestClassifier()
random_forest_classifier.fit(x_train,y_train)
rfc_y_pred=random_forest_classifier.predict(x_test)

print("Random Forest Classifier accuracy score",accuracy_score(y_test,rfc_y_pred))
print("Confusion Matrix")
print(confusion_matrix(y_test,rfc_y_pred))

print("Accuracy score looks good and confusion matrix also shows there are good predictions for label 0")

Random Forest Classifier accuracy score 0.9450717119316447
Confusion Matrix
[[ 222  368]
 [ 172 9069]]
Accuracy score looks good and confusion matrix also shows there are good predictions for label 0


## 3) Ada Boost Classifier

In [41]:
ada_boost_model=AdaBoostClassifier()
ada_boost_model.fit(x_train,y_train)
ada_boost_y_pred=ada_boost_model.predict(x_test)

print("Ada Boost Classifier accuracy score", accuracy_score(y_test,ada_boost_y_pred))
print("Confusion Matrix")
print(confusion_matrix(y_test,ada_boost_y_pred))

print("Accuracy looks good but from confusion matrix it looks to be bias model for label 1")

Ada Boost Classifier accuracy score 0.9400874783847014
Confusion Matrix
[[   1  589]
 [   0 9241]]
Accuracy looks good but from confusion matrix it looks to be bias model for label 1


## 4) Gradient Boosting Classifier

In [44]:
grad_boost_model=GradientBoostingClassifier()
grad_boost_model.fit(x_train,y_train)
grad_boost_y_pred=grad_boost_model.predict(x_test)

print("Accuracy score of Gradient Boosting Classifier",accuracy_score(y_test,grad_boost_y_pred))
print("Confusion Matrix")
print(confusion_matrix(y_test,grad_boost_y_pred))

print("Accuracy looks to be good still from confusion matrix we could summarize it has bias model for label 1")

Accuracy score of Gradient Boosting Classifier 0.9405960736445936
Confusion Matrix
[[   7  583]
 [   1 9240]]
Accuracy looks to be good still from confusion matrix we could summarize it has bias model for label 1


### Looking through Accuracy Score and Confusion matrix, we can choose Random Forest Classifier for predicting test data

In [45]:
df_test_data=pd.read_csv(r"C:\Users\212466649\jupyter\Course End Projects\2) Amazon.com - Employee Access\Dataset for the project\test\test.csv")

In [46]:
df_test_data.head()

id  RESOURCE  MGR_ID  ROLE_ROLLUP_1  ROLE_ROLLUP_2  ROLE_DEPTNAME  \
0   1     32642    7792         118573         118574         117945   
1   2      4696   14638         117961         118343         118514   
2   3     22662    1760         118887         118888         120171   
3   4     75078    7576         117961         118052         120671   
4   5     39879   55668         117902         118041         117945   

   ROLE_TITLE  ROLE_FAMILY_DESC  ROLE_FAMILY  ROLE_CODE  
0      136261            128463       292795     119082  
1      118321            289122       255851     118322  
2      118396            255118       118398     118399  
3      118321            117906       257051     118322  
4      135951            134458        19776     119082

In [48]:
test_data=df_test_data.drop('id',axis=1)

In [50]:
df_test_data.shape


(912363, 10)

In [51]:
test_data.shape

(912363, 9)

In [52]:
rfc_y_pred_test_data=random_forest_classifier.predict(test_data)


In [53]:
test_data['ACTION']=rfc_y_pred_test_data

In [54]:
test_data.head()

RESOURCE  MGR_ID  ROLE_ROLLUP_1  ROLE_ROLLUP_2  ROLE_DEPTNAME  ROLE_TITLE  \
0     32642    7792         118573         118574         117945      136261   
1      4696   14638         117961         118343         118514      118321   
2     22662    1760         118887         118888         120171      118396   
3     75078    7576         117961         118052         120671      118321   
4     39879   55668         117902         118041         117945      135951   

   ROLE_FAMILY_DESC  ROLE_FAMILY  ROLE_CODE  ACTION  
0            128463       292795     119082       1  
1            289122       255851     118322       1  
2            255118       118398     118399       1  
3            117906       257051     118322       1  
4            134458        19776     119082       1

In [56]:
test_data['ACTION'].unique()

array([1, 0], dtype=int64)

In [58]:
test_data['ACTION'].value_counts()

1    899953
0     12410
Name: ACTION, dtype: int64

In [59]:
test_data

RESOURCE  MGR_ID  ROLE_ROLLUP_1  ROLE_ROLLUP_2  ROLE_DEPTNAME  \
0          32642    7792         118573         118574         117945   
1           4696   14638         117961         118343         118514   
2          22662    1760         118887         118888         120171   
3          75078    7576         117961         118052         120671   
4          39879   55668         117902         118041         117945   
5          34026   25242         118555         118178         118320   
6          25753    2679         122880         122974         117945   
7          32642   54271         117902         118041         117945   
8          41372   41760         118315         118316         123656   
9          25753    2679         122880         122974         117945   
10         45990   20219         119280         119281         117945   
11         15714   46612         118752         119070         120995   
12         44984   46612         118752         119070         120995   
13         42031  151283         118315         118463         118522   
14         76873   32242         117961         118327         253965   
15         28294   50793         117961         118052         120096   
16         40997   16588         119920         119921         137107   
17         34582    6278         117961         118343         120722   
18         73561   13845         117961         117962         120526   
19        116246    1140         117961         117962         118352   
20         82337   54684         117961         117962         118910   
21         18418    6257         117961         118343         120722   
22         20226  283684         118752         119070         118754   
23         28294    6482         117961         118343         118992   
24         75943    3763         117961         118300         120059   
25         46048    2270         117961         118413         121567   
26         45974   15644         118752         118753         117945   
27         74463    4571         117961         118225         119924   
28         79299    7790         118573         118574         117945   
29         15716  223988         117902         118041         117945   
...          ...     ...            ...            ...            ...   
912333     73144   51326         118887         118888         118631   
912334     25753    2679         122880         122974         117945   
912335     41594    4589         117961         118327         120383   
912336      6104    4721         117961         118386         119214   
912337     14570   25445         118023         118024         117895   
912338     41642   69637         119062         119091         118992   
912339     14818   27214         117961         118386         118733   
912340     41116   27214         117961         118386         118692   
912341     73756   17046         117902         118041         117945   
912342     22402   79366         117961         118413         120526   
912343     40462    6257         117961         118343         120722   
912344     15716   59230         119280         119281         117945   
912345     75078   28245         118315         118463         123089   
912346     25753   46609         122532         122533         117945   
912347      1281    1325         117961         117962         118910   
912348     77203   15417         117961         119256         119257   
912349     43503   72209         117961         118343         124948   
912350     32642   20219         119280         119281         117945   
912351     79092  120806         117961         118446         118447   
912352     41594   28590         117961         118327         120685   
912353      4675   23347         117961         118052         119408   
912354     22313   55666         117902         118041         118556   
912355     20487    4533         117961         118343         118